apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    app: service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: server:latest
        imagePullPolicy: Never